### ISSUE TITLE
Error during activation after a "fresh installation"

### ISSUE THREAD

**Issue by fabianbormann** [BabylonJS/BlenderExporter#1]
Hi there,
I followed the [installation instructions](https://doc.babylonjs.com/resources/blender#installation) up to the point
" - Check the box to enable it. "

But when I try to activate the plugin it results in the error below:

> Traceback (most recent call last):
  File "/Applications/Blender/blender.app/Contents/Resources/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/Users/username/Library/Application Support/Blender/2.79/scripts/addons/babylon_js/__init__.py", line 86, in <module>
    from . import light_shadow
  File "/Users/username/Library/Application Support/Blender/2.79/scripts/addons/babylon_js/light_shadow.py", line 168, in <module>
    default = False
AttributeError: 'RNA_Types' object has no attribute 'Light'

I use the blender version 2.79b (2.79b 2018-03-22, Blender Foundation) on mac os 10.14.2 and it's the first time that I'am trying to use this plugin so I had no old version to uninstall.

Thanks for helping 😊

**Comment by Palmer-JC** [comment]
Ah, the 6.1 version is for the redesigned Blender 2.80.  While Blender 2.80 is not production until July, the API is now frozen.  If you still need for 2.79, you need to use 5.6 in deprecated dir.

6.1 is the first version which exports PBR & works with material nodes without resorting to baking.  FYI, PBR is not the default.  You need to switch it on in world properties.  Thinking about changing it to default.
