### ISSUE TITLE
Logging bug in texture.py 

### ISSUE THREAD

**Issue by u382514** [BabylonJS/BlenderExporter#10]
There is an error in code in the texture.py file for logging which throws an error on export for a warning:

`logging.Logger.warn('Texture is not mapped as UV or UV2, assigned 1', 5)`

'logging' does not exist. Should be:

`Logger.warn('Texture is not mapped as UV or UV2, assigned 1', 5)`

Is this repo open to having more contributors/pulls or shall we always just go through issues? Seems more productive to have forward progressing dialog through relevant pull requests and enhancements (through issues) than forking.

**Comment by Palmer-JC** [comment]
Thanks, I am planning to do a release in the next week for a fix for an metal / roughness / ambient occlusion texture.  Will take take of this.  If you want to do a PR ok.

As far as, PR's vs  direct,  This is a very mature repo / 5 year old code base.  Except for the 2.80 redesign, it gets few updates.  PR is what I prefer & I also prefer not including the changes to the zip file in them.  I religiously update the version # for updating the zip.

**Comment by Palmer-JC** [comment]
Taken care of in the latest release, thanks!
