### ISSUE TITLE
PBR Sheen value export is breaking import in Babylon 4.0.3

### ISSUE THREAD

**Issue by osmanzeki** [BabylonJS/BlenderExporter#11]
# Versions
- Blender: **2.80**
- Exporter: **6.2.3**
- BabylonJS: **4.0.3**

# Bug Description

The Babylon Blender Exporter causes errors in the stable version of BabylonJS on NPM (v4.0.3) due to a bug/typo in the code of BabylonJS itself relative to the way it parses `sheen` values.

The problem comes from the fact that the `pbrMaterial.ts`, `pbrSpecularGlossinessMaterial.ts` and `pbrMetallicRoughnessMaterial.ts` are parsing the `sheen` value incorrectly by using the `brdf` value which can be `null` at that point.

To be clear, this bug **has been corrected** in later versions of Babylon (4.1.0+) but those versions are not yet available on NPM as stable which puts us in a catch-22 scenario. Meaning that the latest stable version of the Exporter is not compatible with the latest stable version of BabylonJS.

# Solutions / Workarounds

A workaround would be to hack the Babylon Exporter to no longer write the `sheen` value to the exported files (thus avoiding the runtime error in-engine).

I believe commenting out these lines should do the trick for now. Very hacky, but it should work hopefully:
https://github.com/BabylonJS/BlenderExporter/blob/master/src/babylon_js/materials/material.py#L307:L318

Another option would be to hack the engine itself to fix the bug in my local version of Babylon 4.0.3 just like it was done in later versions. Not ideal since I'm using Babylon directly from NPM and not compiling from source.

# References

Problem Commits (and lines) here:
https://github.com/BabylonJS/Babylon.js/blob/v4.0.0/src/Materials/PBR/pbrMaterial.ts#L764
https://github.com/BabylonJS/Babylon.js/blob/v4.0.0/src/Materials/PBR/pbrSpecularGlossinessMaterial.ts#L120
https://github.com/BabylonJS/Babylon.js/blob/v4.0.0/src/Materials/PBR/pbrMetallicRoughnessMaterial.ts#L130

Seems to have been fixed in this commit here:
https://github.com/BabylonJS/Babylon.js/commit/d9a349a5b6d3a43bdf1be63e0462ddca1f0267f8

**Comment by Palmer-JC** [comment]
Thanks for documenting this.  If you would notice in your proposed solution, there is already the writing out isEnabled twice.  This change occurred right after 4.0 went out, and I pointed out I needed to write private members to JSON, so they made them public.  It is easy to write small stuff twice.  I just need to remember to delete that after 4.2 comes out.

Not writing stuff is not easy at a repo level.  It is also a transitory problem that goes away on it own.  For non npm is already has.  I suggest for your work, just delete the section which exports it, or maybe just edit the babylon files.  Which ever is easier.

I really think this is more of a problem that the npm is only published periodically.

**Comment by osmanzeki** [comment]
Indeed no worries, I just wanted to document this behaviour as you mentioned as I had a hard time figuring out what was going on when upgrading to Blender 2.8x for my workflows (I have a lot of automated exports to Babylon in python and Blender).

I fixed it exactly as you proposed, by commenting out the section that writes the `sheen` stuff for the moment. Indeed when 4.2 is released and npm is all synced, I will reinstate the latest Babylon Blender exporter in my workflow. :)

Thank you!
