### ISSUE TITLE
Blender exporter Materials to PBRMaterials Typescript type conflict

### ISSUE THREAD

**Issue by peterkimga** [BabylonJS/BlenderExporter#12]
Hi

exporter V 6.2.3, Blender 2.81

While exporting mesh to .babylon file and checking option:

World Properties > Babylon.js ver 6.2.3 > Use PBR Materials

I got when Loading the scene with SceneLoader.Append a situation that I would like to modify ambientColor for all materials in mesh.materials array.

for (let index = 0; index < scene.materials.length; index++) {
        const material = scene.materials[index];
        material.ambientColor = new Color3(1, 1, 1);
      }

And linter for typescript is throwing an error:

Property 'ambientColor' does not exist on type 

Ok, so I cast the material to PBRMaterial:

const material = scene.materials[index] as PBRMaterial;

And this error is gone but then I got a new one:

error  Do not use any type assertions  @typescript-eslint/consistent-type-assertions

The solution to this is for me now:

const material = scene.materials[index] as PBRMaterial; // eslint-disable-line @typescript-eslint/consistent-type-assertions
       
But I think if I'm selecting Use PBR Materials my materials in the scene will all be PBRMaterials and they should have a proper meshes type so Materials[] | PBRMaterials[].

Regards

**Comment by Palmer-JC** [comment]
Think this should probably live on the [forum](https://forum.babylonjs.com/).  The JSON / .babylon loader gets it into the scene, after that it should not matter where it came from.

**Comment by peterkimga** [comment]
Yes, that should be a general approach that I can have any material on my esh and not have type conflict while trying to access it.
