### ISSUE TITLE
Problems with blender editing properties

### ISSUE THREAD

**Issue by HelloWorld-orz** [BabylonJS/BlenderExporter#13]
![image](https://user-images.githubusercontent.com/15843581/71969265-46c80c80-3241-11ea-9238-69ba8de6281a.png)
duplicate linked  => BABYLON.InstancedMesh
Some properties of the InstancedMesh object are separated, such as: tag pickable .....
but there seems to be no way to edit separately in blender

**Comment by Palmer-JC** [comment]
That is just how Blender defines duplicate linked, as meshes which share the same data properties.  Exporter custom properties included in that.  Tags, pickable, & checkCollisions are in the export for instances, but always the same value.  Only location, rotation, & scale does Blender keep unique.
