### ISSUE TITLE
exporting scenes with blender 2.8 with v6 in contrast to 2.7 with v5 results in much bigger file sizes

### ISSUE THREAD

**Issue by BEMA03-SMS** [BabylonJS/BlenderExporter#14]
I used the blender plugin to export some obj files to the Babylon format. After switching to 2.8 I realize that the resulting Babylon files getting bigger than before. A 70MB obj file resulted in a 100MB Babylon file, before with blender 2.7 and exporter version v5 it resulted in a 33MB file size. 

I switched back to blender 2.7 and its maybe also possible that it was settings related but some further investigation would be nice.

**Comment by Palmer-JC** [comment]
This really should be done in the forum, [https://forum.babylonjs.com](https://forum.babylonjs.com).  Quick take is it could also be how the obj import to Blender may have changed.

Check your corresponding export log files from the 2 exports as well.
