### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by undefinederror** [BabylonJS/BlenderExporter#16]
I am on blender 2.81, I have downloaded the repo zip file as per https://doc.babylonjs.com/resources/blender

Instruction there don't seem to apply anymore. Add-ons in this version are under Edit=>Preferences=>Add-ons, but that is quick to find and no problem.
After installing the zip file Babylon add on is nowhere to be found.
This is the log
![image](https://user-images.githubusercontent.com/8209966/73680828-48101c00-46bd-11ea-918c-e69521d8c224.png)

**Comment by undefinederror** [comment]
Alright... 
so the zip file from the repo **does** need to be unzipped, and within that there is another zip named Blender2Babylon-6.2.zip. That is the one to install in Blender.
Sorry I just installed Blender and I am absolutely not familiar with add-on installation. But for people like me the instructions at https://doc.babylonjs.com/resources/blender will definitely result confusing,
![image](https://user-images.githubusercontent.com/8209966/73681442-a1c51600-46be-11ea-8ea1-683afdc95748.png)

**Comment by Palmer-JC** [comment]
For future reference, just click the **Blender2Babylon-6.2.zip** file.  It will bring you to a page with a download button.  You do not need to bring down the whole repository.  That probably be added, but I do not do that part.

**Comment by undefinederror** [comment]
Yes you are right, it was actually pretty obvious. I guess I was rushing things that day and ended up only skimming through documentation, eventually wasting more time than I was trying to save 😄
