### ISSUE TITLE
No exporter panel for Scene Properties in blender v2.82.7

### ISSUE THREAD

**Issue by griga** [BabylonJS/BlenderExporter#19]
Hi there! 

Blender version: 2.82.7
BlenderExporter version: 6.3.1

No exporter panel for Scene Properties
![image](https://user-images.githubusercontent.com/512051/76648029-9212da00-6566-11ea-8370-a8148ca52389.png)

However exporter panel exists for Mesh, Lights, Camera, Material and World panels
![image](https://user-images.githubusercontent.com/512051/76648391-4a408280-6567-11ea-97f8-50adeeb6ca4e.png)

**Comment by Palmer-JC** [comment]
Since exporter version 6.0 & Blender 2.80,  The properties which used to be on the scene tab have been consolidated onto the World Tab.
