### ISSUE TITLE
Can't Install Addon

### ISSUE THREAD

**Issue by hgmvu** [BabylonJS/BlenderExporter#20]
I am trying to install the Exporter for Blender 2.8.2 but it seems like the Addon can't be installed. There's no way to find out why. The Addon didn't show up in the list either. Hope s.o can help.

**Comment by Palmer-JC** [comment]
If there was a problem you could open the Blender Console, and see what got
logged.

**Comment by rob-myers** [comment]
I also cannot install it (OSX and Blender v2.82.7).

Launching from terminal shows:
```py
Modules Installed () from '/Users/robmyers/Downloads/Blender2Babylon-6.3.zip' into '/Users/robmyers/Library/Application Support/Blender/2.82/scripts/addons'
```
but the extension does not appear in the Addon list.

**Comment by Palmer-JC** [comment]
Do not have that platform.  Suggest a Blender restart.  Also, there is a
special category 'Babylon.js' you can switch to.  Got tired long ago
searching, so made a shortcut for myself.

**Comment by arigbs** [comment]
Got the same issue here....

**Comment by arigbs** [comment]
Figured this out. If this problem persists, ignore the installation instruction and extract the zip file downloaded from the repo. You'll find another zip file in a sub folder there labelled "Blender2Babylon-6.3.zip". That's the one to install.

**Comment by doctorjana** [comment]
> 
> 
> Figured this out. If this problem persists, ignore the installation instruction and extract the zip file downloaded from the repo. You'll find another zip file in a sub folder there labelled "Blender2Babylon-6.3.zip". That's the one to install.

This worked for me. Thanks!

**Comment by james3roberts** [comment]
You my friend are a bad MoFo. Hours wasted trying to figure this out. You will be my hero for the next 8.5 days!!

**Comment by NataliTim** [comment]
@arigbs Thank you!
