### ISSUE TITLE
Exporting instances of collections doesn't work

### ISSUE THREAD

**Issue by shasaur** [BabylonJS/BlenderExporter#23]
### Problem

When you export a collection and an instance of that collection, only the mesh data of the original collection seem to get exported. For any instances of the collection, only the position seems to remain.

My question is: is this a problem with my set-up / the way I'm exporting, or is it that this is not implemented yet?

### Reproduction steps

- Select a mesh
- Object > Collection > Create new collection (let's use name 'My Collection')
- Go to Add > Collection Instance > 'My Collection'
- File > Export > Babylon
- Import into a [babylon viewer](https://sandbox.babylonjs.com/)
- See that there is no mesh data for the instance of your collection, only the original 'My Collection' mesh

### Set-up
- Blender 2.82
- macOS Cataline (10.15.4)

**Comment by ma-ko91** [comment]
Hey,

I've got a similar problem when importing a fairly complex scene from blender into Babylon.
Also the instances move to the positions of the original meshes when playing animations.

Just wanted to drop by and ask if you found a solution for your problem.

**Comment by Palmer-JC** [comment]
This is not supported.  Would not perform very well, if it did.  If this is
just background stuff that does not move, I would join all meshes, then
duplicate linked.  This will result in a multimaterial mesh, any duplicate
linked will be a mesh instance.  The number of draw calls will be equal to
the number of materials
