### ISSUE TITLE
Babylon Exporter 3D Max plugin is having issues on exporting animated character

### ISSUE THREAD

**Issue by rvnosa** [BabylonJS/BlenderExporter#28]
I am having issue on exporting the animated character from max to babylon, still getting issues

[video sample.zip](https://github.com/BabylonJS/BlenderExporter/files/4998410/video.sample.zip)

[testRig.zip](https://github.com/BabylonJS/BlenderExporter/files/4998404/testRig.zip)

**Comment by Palmer-JC** [comment]
Sorry for not noticing this, but This repo is specific for Blender.  You need to post this on this repo, https://github.com/BabylonJS/Exporters
