### ISSUE TITLE
Cameras ellipsoïds coordinates not converted

### ISSUE THREAD

**Issue by storkweb** [BabylonJS/BlenderExporter#30]
Hi,
I've found that when defining a camera ellipsoid in Blender (2.9.1) it's coordinates are not converted in the .babylon exported file (with exporter plugin v6.4.5) as the rest of the coordinates are. Z and Y coordinates should be exchanged, they currently are not.
I know it simple to enter them in the right (wrong ?) order or to translate them after load in BJS, but it should be a simple fix, if you can find time to include it in the next release :-)

Anyway, thanks a lot for the great job !

**Comment by Palmer-JC** [comment]
Ellipsoid is a custom property for the exporter.  It is not in use for blender, so there would be no need to swap.

Checking current framework, I am not even seeing we have that property anymore, so looks like it is not going to do anything anyway.

**Comment by Palmer-JC** [comment]
Will keep for 2.93 exporter.  Have added a mouse hover description of 
`Not used except for a collision system.  Enter Coordinates in Y-UP terms`
