### ISSUE TITLE
UV smart_project error in Blender 2.91

### ISSUE THREAD

**Issue by r-arvind** [BabylonJS/BlenderExporter#34]
Blender 2.91 seems to have a few changes in the API.

![image](https://user-images.githubusercontent.com/32129503/101280912-ef844080-37f1-11eb-9854-54283847d763.png)

There's a minor error in the smart_project function.

The [smart_project](https://docs.blender.org/api/2.83/bpy.ops.uv.html?highlight=smart_project#bpy.ops.uv.smart_project) in Blender 2.83 has the parameter named as `user_area_weight`.

The parameter has been switched to `area_weight` in [smart_project](https://docs.blender.org/api/current/bpy.ops.uv.html?highlight=smart_project#bpy.ops.uv.smart_project) in Blender 2.91

I think the renaming is causing this issue. Reporting it here so that it can be looked into while porting the exporter for Blender 2.9x

**Comment by r-arvind** [comment]
Okay, I simply tried renaming `user_area_weight` to `area_weight` in the addon to see if it works out. It's still giving the same error :sob: 

![image](https://user-images.githubusercontent.com/32129503/101281346-691d2e00-37f4-11eb-974d-b104d84e2a83.png)

I guess there's something else wrong with it

**Comment by r-arvind** [comment]
Surprisingly, the error has changed!
It's showing this now:
```
Python: Traceback (most recent call last):
  File "/home/arvind/.config/blender/2.91/scripts/addons/babylon_js/__init__.py", line 65, in execute
    exporter.execute(context, self.filepath)
  File "/home/arvind/.config/blender/2.91/scripts/addons/babylon_js/json_exporter.py", line 115, in execute
    mesh = Mesh(object, scene, self)
  File "/home/arvind/.config/blender/2.91/scripts/addons/babylon_js/mesh.py", line 146, in __init__
    recipe = BakingRecipe(bpyMesh, exporter)
  File "/home/arvind/.config/blender/2.91/scripts/addons/babylon_js/materials/baking_recipe.py", line 105, in __init__
    self.bakedMaterial.bake(bpyMesh, self)
  File "/home/arvind/.config/blender/2.91/scripts/addons/babylon_js/materials/material.py", line 136, in bake
    uv.active = True
AttributeError: 'NoneType' object has no attribute 'active'

location: <unknown location>:-1
```

I'm stuck fixing errors recursively :sob: I guess I'll downgrade to 2.8x for now.

On a side note, thanks for this amazing addon. Any plans to port it to Blender 2.9x? I'll be happy to help if needed.

**Comment by Palmer-JC** [comment]
My experience with the very long 2.80 dev cycle was API would change over
and over.  Now with Blender in a 4 release LTS cycle (0, 1, 2, 3) or (2.90,
2.91, 2.92, 2.93) I do not have the time to keep up.

I run 2.83 LTS.  When 2.92 hits, March 2021, I will probably see what is
what.  Even then, I will not do it on the master branch,

**Comment by Palmer-JC** [comment]
Changed in exporter for next release, but nothing published yet

**Comment by Palmer-JC** [comment]
complete in 2.93 exporter
