### ISSUE TITLE
Optionally include Blender Custom Properties in babylon metadata

### ISSUE THREAD

**Issue by timshannon** [BabylonJS/BlenderExporter#42]
Blender [Custom Properties](https://docs.blender.org/manual/en/2.79/data_system/custom_properties.html) allow for adding arbitrary properties to meshes other nodes, including things like cameras and lights.

When you export a model from Blender to GLTF, it puts any added custom properties into the GLTF "extras", which when imported into babylon gets added to the node's metadata under the `gltf.extras` key.  It would be nice to have a similar option with this exporter.  

The custom properties could be added under a `blender` tag in a node's metadata similar to how the gltf pipeline handles this.

**Comment by apetkov-so** [comment]
This would be a very useful feature.

**Comment by Palmer-JC** [comment]
Meshes have a 'tags' property and in the exporter properties.  Arbitrary
properties are not supported in the .babylon format, so the property would
need to be something that was serialized, or it would be ignored.

**Comment by apetkov-so** [comment]
I was thinking about writing the custom properties into the mesh's `metadata`, as a JSON string. Except for "Python", the types (Float, FloatArray, Integer, IntegerArray, String) map directly to JSON, so it seems like a good place to store this data. But I am not familiar with the plugin's details, so I'm not sure how difficult this would be.

**Comment by Palmer-JC** [comment]
I would not do it, but you may PR it if you want.

**Comment by Palmer-JC** [comment]
Completed
