### ISSUE TITLE
No material when exporting

### ISSUE THREAD

**Issue by sneakyocean** [BabylonJS/BlenderExporter#48]
I am exporting this bat out from blender 2.93, but when I view it in sandbox.babylonjs.com it says that there is not any materials assigned, which though the log file claims it is true, acknowledges that the materials exist.
I am attaching the texture, babylon file, and blender file: [Stuff.zip](https://github.com/BabylonJS/BlenderExporter/files/6744341/Stuff.zip)

This is the log output:
<pre>
========= Writing of JSON file started =========
writing mesh:  Quad Sphere
writing mesh:  Sphere
========= Writing of JSON file completed =========
========= end of processing =========
elapsed time:  0 min, 1.6083 secs
========= Conversion from Blender to Babylon.js =========
Scene settings used :
Inline textures     :  false
Material Type       :  PBR
Positions Precision :  4
Normals Precision   :  3
UVs Precision       :  3
Vert Color Precision:  3
Mat Weight Precision:  2
Keep Z-up r-handed  :  no
Texture directory   :  /home/user/Downloads/
Python World class constructor completed
processing begun of camera (UniversalCamera):  Camera
processing begun of mesh:  Quad Sphere
processing begun of material:  Bat
processing texture bat
texture type:  diffuseTexture, mapped using: "UVMap"
num positions      :  1893
num normals        :  1893
num tangents       :  0
num uvs            :  3786
num uvs2           :  0
num colors         :  7572
num triangles      :  3224
processing begun of mesh:  Sphere
<b>WARNING: No materials have been assigned: </b>
num positions      :  2462
num normals        :  2462
num tangents       :  0
num uvs            :  4924
num uvs2           :  0
num colors         :  0
num triangles      :  4224
processing begun of light (DIRECTIONAL):  Sun
processing begun of light (DIRECTIONAL):  Sun.001
processing begun of light (DIRECTIONAL):  Sun.002
========= Writing of JSON file started =========
writing mesh:  Quad Sphere
writing mesh:  Sphere
========= Writing of JSON file completed =========
========= end of processing =========
elapsed time:  0 min, 1.7002 secs

Info: Saved "Oneeyed-evilbat.blend"
</pre>

**Comment by sneakyocean** [comment]
I found that it does work, but there is a warning saying no material applied, which is weird.

**Comment by Palmer-JC** [comment]
Please use https://forum.babylonjs.com/ for this type of question.  I do not often get involved with peoples scenes, but beyond looking at the log file, but others may.

Also, posting of materials properties area when `Sphere` is the active / selected mesh will probably be very useful.  Closing this.
