### ISSUE TITLE
Refactoring of addon

### ISSUE THREAD

**Issue by florianfelix** [BabylonJS/BlenderExporter#5]
Hi. This really is not an "issue", but

I have started refactoring the addon.
My immediate goal is to remove all the code in the to_json functions where the file gets written 'by hand'. I have experienced slow exports and my thinking is that all this writing to the file_handler could be one slow point.
Instead i started adding dictionaries to all the object classes. The idea is to collect all the dicts in the end and write the file in one last step. For the moment the original code is mostly untouched apart from some splitting into more files and a replacemnt of the registering in the init file.
Ideally the collecting of the data i am doing now in the collect_data functions should be moved into the classes init functions or the classes could directly subclass from OrderedDict. But i wanted to first see if it works/makes a difference.

Anyways before i continue i just wanted to ask if this is something you would be interested in or if i am just monkeycoding for nothing :)

You can look at the code at:
https://github.com/florianfelix/BlenderExporter/tree/dictwrite

Here:
https://github.com/florianfelix/BlenderExporter/blob/dictwrite/src/babylon_js/mesh_submesh.py
and here:
https://github.com/florianfelix/BlenderExporter/blob/dictwrite/src/babylon_js/mesh_meshinstance.py
you can see what the endgoal should be me thinks.
If we have such classes we can just deliver everything to json.dump and get our final file.

**Comment by Palmer-JC** [comment]
If your primary motivation is time, I would have started by adding time stamping into logging.  This would help narrow down not just your slowness, but anyone's.

I am not in favor of doing this.  My goals were to keep the files as compact as possible.  If that meant the export took a little longer, that was ok.  Having large files, means longer to send them to a client.  This is the area one area that really counts.

Not controlling the number of digits means every single number in the file is going to have 7 or 8 decimals.  The file size is going to explode.  I go to a lot of trouble to even allow control of the number of digits by data type.  If JSON allowed for numbers without a leading zero, I could have chopped off a tenth of the file more.

Actually, if writing out the stuff is the bottle neck,  how the significant digits are formatted might be partly responsible.  That code is also used when the testing of whether the vertices are duplicates.  This is likely an area responsible for some time.

**Comment by florianfelix** [comment]
That doesn't seem to be a problem. Here is a custom jsonencoder where the floats get formatted to 3 digits (after.) only. This can be customized as needed.

Sorry forgot to put link:
https://github.com/florianfelix/BlenderExporter/blob/dictwrite/src/babylon_js/export_json_new.py

I have plugged in your format_f function there and it 'just works'.
What would be lost would be granular control of precision for different float 'types'.

Example output
[sampleout.babylon.txt](https://github.com/BabylonJS/BlenderExporter/files/3545147/sampleout.babylon.txt)

**Comment by florianfelix** [comment]
I have modified the encoder. This way arbitrary precisions for different datatypes can be achieved at time of serialization:
https://github.com/florianfelix/BlenderExporter/blob/dictwrite/src/babylon_js/export_json_new.py

**Comment by Palmer-JC** [comment]
I am not sure what would be gained, but as long you can this to completion, and tested, I have no problem.  I have for the most part been doing this almost solely from David Catuhe single file, single pass original code from 2014.

**Comment by florianfelix** [comment]
Maybe the final size could be reduced by using ubjson:
https://pypi.org/project/py-ubjson/
https://www.npmjs.com/package/@shelacek/ubjson

**Comment by Palmer-JC** [comment]
Interesting.  If done would need to be an option.  Also, would not want as part of an initial PR.  PR's are not expensive.  Is the reading of binary JSON files widely implemented?

Right now from what I have seen, would remove your linefeed - tab for every number.  I found keeping the length of each line at 50 vertices per line still made it open-able in a text editor, and somewhat still human readable.

**Comment by Palmer-JC** [comment]
Couple other thoughts are that a binary file cannot be GZipped.  After getting the file as small as possible, GZip reduces the transmission by approximately 70%.  

The other is that I do not think we could use the `.babylon` extension, since people make changes to web servers to describe files of that type so they can be compressed for transmission.

**Comment by florianfelix** [comment]
Yep, binary could be suboptimal (just a thought that came to mind) and would require many changes in not controllable places.
The formatting was the standard json indent export option. That cannot be used with a custom encoder anyway. The custom encoder spits out just one line atm (i just format it in vscode if i want to have a look). But custom formatting should also be implementable i think. Could be hidden in a devel option.
