### ISSUE TITLE
physicsImpostors are applied but not assigned to objects

### ISSUE THREAD

**Issue by marcusdiy** [BabylonJS/BlenderExporter#53]
Hi, I was trying to make import a scene with (collider + rigid body) generated in blender.
The scene loads and the objects fall as expected, but there is no way to access the imposter...i wanted to create a joint.
Is there some extra step to assign those properties or is not implemented? 

I will attach both files: blender + export
So you can test it on https://sandbox.babylonjs.com/

![missing-physics-imposter](https://user-images.githubusercontent.com/42746781/144681534-f7d4f154-88fa-4886-85db-8d5bce35af27.JPG)
Thanks

**Comment by marcusdiy** [comment]
Remove .txt from files 😉 
[test-physics-export.babylon.txt](https://github.com/BabylonJS/BlenderExporter/files/7652717/test-physics-export.babylon.txt)
[test-physics-export.blend.txt](https://github.com/BabylonJS/BlenderExporter/files/7652718/test-physics-export.blend.txt)

**Comment by marcusdiy** [comment]
Related:
https://forum.babylonjs.com/t/access-the-physicsimpostor-of-a-mesh-imported-from-blender3d/11519
https://forum.babylonjs.com/t/how-to-use-meshimpostor-with-blender-imported-glb/6724

**Comment by Palmer-JC** [comment]
I know very little about physics engines.  This does not appear to be an exporter issue.  The person who added to the exporter this just put a number corresponding to the imposter type in the `physicsImpostor` property of mesh.  The load does something with that number. 

Whatever this missing object is, I do not believe it is to be provided directly by Blender exporter.  You should raise this on the forum, or look at this in docs.  There is something about joints in the motors section [motors section](https://doc.babylonjs.com/divingDeeper/physics/advancedPhysicsFeatures)
