### ISSUE TITLE
deprecated/Blender2Babylon-5.6.zip is corrupt? missing?

### ISSUE THREAD

**Issue by kevzettler** [BabylonJS/BlenderExporter#6]
I'm trying to download the `deprecated/Blender2Babylon-5.6.zip`  I have tried downloading directly from github and also tried cloning the repository and unzipping manually. I am on OSX and get an error that the unzip fails. The file size is listed as 38.5 KB which seems suspiciously small when compared to the current plugin and the older `io_export_babylon.py`

**Comment by Vinc3r** [comment]
I just tested from a fresh Blender (2.79 of course) install, all is fine here (on Windows).

What says your error?

**Comment by Palmer-JC** [comment]
First, this add-on does not support `manual` un-zipping as an installation method, and has not since for quite a while.  Do you want to look at the files outside of Blender? 

Also, `io_export_babylon.py` is not compressed, which is probably causing your current line of thought.

**Comment by kevzettler** [comment]
<img width="380" alt="Screenshot 2019-09-04 16 52 28" src="https://user-images.githubusercontent.com/126209/64301553-68805280-cf34-11e9-92d1-137014767ff7.png">
@Vinc3r here is screenshot of error

@Palmer-JC are you saying I import the `.zip` directly to blender?

**Comment by Vinc3r** [comment]
Actually that's an OSX user permissions error.

Note that you don't have to unzip :
- in Blender go to File > User Preferences > Add-ons Tab
- (optionnal) remove previous installation if already existing
- install by using Install from File... and select your zip
