### ISSUE TITLE
Install in Blender not registering

### ISSUE THREAD

**Issue by ScoobyTchotchke** [BabylonJS/BlenderExporter#8]
I'm currently trying to install Blender2Babylon-6.2.zip into Blender v2.80, and it does not appear to be registering with Blender.  I don't see the add-on in the list after attempting installation.

**Comment by Palmer-JC** [comment]
If I can assume you are using Blender 2.80, and installing the zip file through the Preferences `Install..` button shown at the top when in the `Add-ons` section, please cut and paste the text from the System Console.  This is shown using the `Window->Toggle System Console` menu.

**Comment by ScoobyTchotchke** [comment]
`Modules Installed () from 'C:\\Users\\scotty\\Downloads\\Blender2Babylon-6.2.zip' into 'C:\\Users\\scotty\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'`

No errors as far as I can see.  That's the only message I receive.

**Comment by Palmer-JC** [comment]
In that case,  are you sure there is no entry in Preferences to turn on?  There is a `Babylon.JS` filter which will cut down looking through long lists.  See:

![preferences](https://user-images.githubusercontent.com/7916131/66331027-a12e9580-e8ff-11e9-8087-56b9374ed284.png)

**Comment by ScoobyTchotchke** [comment]
Nothing, unfortunately:

![Annotation 2019-10-07 124456](https://user-images.githubusercontent.com/3910276/66331340-4c3f4f00-e900-11e9-8ec8-fc3c0b19b0f8.png)

![Annotation 2019-10-07 124605](https://user-images.githubusercontent.com/3910276/66331407-75f87600-e900-11e9-952f-195b0c06021d.png)

**Comment by Palmer-JC** [comment]
Not a lot I can do, but to recommend physically checking that files exist at
`C:\\Users\\scotty\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons`.  If the install actually worked there should be a subdirectory of `babylon_js`.

Bisecting the problem between verifying the files are really there, and failure to recognize their presents, is really the only next move.

**Comment by ScoobyTchotchke** [comment]
Got it.  I couldn't open the zip file, and it appeared to be invalid.  I think what I did was download the zip file from github independently, which produced an invalid zip file.  After cloning the repo and pulling the zip file out of the repo, then using that to import, it works.  Thank you for your time!
