### ISSUE TITLE
Guide doesn't work for me, it also needs updating

### ISSUE THREAD

**Issue by Elrinth** [BabylonJS/BlenderExporter#9]
I just downloaded blender. Which gave me version v2.80.75.
There is no "File -> User Settings" to start with.
There is however a "Edit -> Preferences..."

Then on the left there is an "Add-ons" which you can select.
So I click: "Install..." Then I select a zip I downloaded of this Blender Exporter. Because you don't have any release, I'm assuming it will work with just downloading a zip of the master-branch.
"BlenderExporter-master.zip"
Then I click the "Install Add-on from File...".
Then in the bottom of the program it says:
Modules installed from $PATHTOZIP$  into $PATHTOBLENDER280ADDONFOLDER$

But then I cannot see the "addon" anywhere in Official, Community or Testing. So I can't activate it.

Is this exporter not compatible with Blender 2.80.75? Or am I doing something wrong?

**Comment by Palmer-JC** [comment]
Yes, the guide is pre-Blender 2.80.  You got very close though.  It shows in community for me.

There used to be multiple public exporters in the past for BJS (I pulled the JS generator from public view). I put them in their own category,  `BabylonJS`, for that reason.  I'll put it on my list to switch the cat to `import-export` for future releases.

**Comment by Elrinth** [comment]
Thank  you for the response. Ok Babylon won't show up for mein blender add-ons. Not sure what I'm doing wrong. Maybe I need to start blender as administrator? I am using Win 10.
But anyways, I satisfied with using the gltf format.
